name: ASSERT - AweSome SoftwarE Research Team
url: http://assert-kth.github.io

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: postdoc
    name: PostDoc
  - key: grad
    name: Graduate Students
  - key: engineer
    name: Research Engineers
      #  - key: ugrad
      #    name: Undergraduate Students
      #  - key: ugrad-alum
      #    name: Past Undergraduate Students
      #  - key: collab
      #    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
